export enum ErrorCode {
    // Authentication errors
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
    AUTH_TOKEN_REVOKED = "AUTH_TOKEN_REVOKED",
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID",
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",

    // User errors
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    USER_ACCOUNT_SUSPENDED = "USER_ACCOUNT_SUSPENDED",
    USER_ACCOUNT_DELETED = "USER_ACCOUNT_DELETED",

    // Expense errors
    EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND",
    EXPENSE_DUPLICATE_DETECTED = "EXPENSE_DUPLICATE_DETECTED",
    EXPENSE_FORBIDDEN = "EXPENSE_FORBIDDEN",

    // Validation errors
    VALIDATION_FAILED = "VALIDATION_FAILED",
    INVALID_INPUT = "INVALID_INPUT",

    // Resource errors
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    RESOURCE_FORBIDDEN = "RESOURCE_FORBIDDEN",

    // Generic errors
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    BAD_REQUEST = "BAD_REQUEST",
}
